version: '3'
services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ../volumes/nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nextcloud_user
      - POSTGRES_PASSWORD=nextcloud_secret
      - POSTGRES_DB=nextcloud_store

  app:
    image: nextcloud:22
    restart: unless-stopped
    links:
      - db:db-container
    volumes:
      - ../volumes/nextcloud/app/html:/var/www/html
    networks:
      default:
        ipv4_address: 172.16.1.20
    environment:
      - POSTGRES_HOST=db-container
      - POSTGRES_USER=nextcloud_user
      - POSTGRES_PASSWORD=nextcloud_secret
      - POSTGRES_DB=nextcloud_store
      - TRUSTED_PROXIES=172.16.1.10
    extra_hosts:
      - "host.docker.internal:host-gateway"

  proxy:
    image: nginx:1.21
    restart: unless-stopped
    command: >
      sh -c
      "
      chmod 444 /proxy_assets/cert/ca/*
      && rm /etc/nginx/conf.d/*
      && envsubst '
      $$CONF_UPSTREAM
      $$CONF_SERVER_NAME
      $$CONF_SERVER_CERT
      $$CONF_SERVER_KEY
      $$CONF_CERTS_DIR
      $$CONF_HTTPS_PORT
      '
      < /proxy_assets/conf/default.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'
      "
    links:
      - app:app-container
    ports:
      - "8040:443"
      - "8041:80"
    volumes:
      - ./assets/conf:/proxy_assets/conf:ro
      - ./assets/cert/ca:/proxy_assets/cert/ca
      - ./assets/cert/server:/proxy_assets/cert/server:ro
    environment:
      - CONF_UPSTREAM=app-container
      - CONF_SERVER_NAME=myserver.local
      - CONF_SERVER_CERT=/proxy_assets/cert/server/dummy-server.crt
      - CONF_SERVER_KEY=/proxy_assets/cert/server/dummy-server.key
      - CONF_CERTS_DIR=/proxy_assets/cert/ca/
      - CONF_HTTPS_PORT=8040
    networks:
      default:
        ipv4_address: 172.16.1.10
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    ipam:
      config:
        - subnet: "172.16.1.0/24"
          gateway: "172.16.1.1"
